ARDUINO_DIR ?= $(HOME)/local/arduino/1.0
ARDUINO_ETC_PATH ?= /etc
AVR_TOOLS_PATH = /usr/bin
SHELL = /bin/bash

TARGET       = LightwallPlayer3
BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB*

#ARDUINO_LIBS = Wire

include Arduino.mk
